#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : simplejson
Version  : 3.8.2
Release  : 23
URL      : https://pypi.python.org/packages/source/s/simplejson/simplejson-3.8.2.tar.gz
Source0  : https://pypi.python.org/packages/source/s/simplejson/simplejson-3.8.2.tar.gz
Summary  : Simple, fast, extensible JSON encoder/decoder for Python
Group    : Development/Tools
License  : AFL-2.1 MIT
Requires: simplejson-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : py
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
simplejson is a simple, fast, complete, correct and extensible
JSON <http://json.org> encoder and decoder for Python 2.5+
and Python 3.3+.  It is pure Python code with no dependencies,
but includes an optional C extension for a serious speed boost.

%package python
Summary: python components for the simplejson package.
Group: Default

%description python
python components for the simplejson package.


%prep
%setup -q -n simplejson-3.8.2

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python setup.py test
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
